title: Test Workshop
remote_theme: ubc-library-rc/rc-workshop-template
footer_content: "<a href=\"https://github.com/ubc-library-rc/Geospatial-Analysis-Visualization-with-Python/\">View in GitHub</a>"